language: node_js
node_js:
  - "6"

env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: "E55QkoZaFfaWmy3NuixKiQachN7SY4EQcdITBlIP6oe06ycOYubSW8oZryEoHtF/Mgw78aYYKwkJ3eEjsrOCr3IGfst7biwXKpcboFFXiM9uPv6fPFUbRFuyL+zZCYpX1fzzMi1d1L1/E7f6zZZKeaGO0y0WIchOiqIvh6w/L3F/d5TYcoTauymNp8WqGZaJN2gexHm+D9s6pL8iQYM5+Ujzb0WLpRYn7BajTUhZbTw6/bVHJRmxr+k106kQDewzQZbf7bZHofjxUrbxVEfowKuUklzgKDgSyMzgIMpXnsq5n/ydaXQt0jftibi05mycStDe55rC4adwnM+r+jA+wzVfFtyFQVWoiQeUmQ+dRqmFm6xDuXrrgkQeF9z3cf78HSXClDlo0oFrAj3yFGZOKOEZQEMs30CSgkMkTljxhVgcjawt5tEoxEtHAQiklVmUC+VTkLwW1olrWj3mXuT8Bv9b35xtqHM2Y4f3W+E7M3A7XvMtEr1vQOgHVfYQTEHSdYQ1ddyuF9bOJNTONOj/hsJi0Iu+s5OpR4N/QqfkmGA5hQ0+dz0cNp+p/H/t3PDlVsklVsk08vUHiYha8Op8hml/JgXQLimkeJYYUC9QcwkbIzteNfBdo4TqpI/qZ/OPpSO9Sw4VZOf54voaIHH+TdcCtKx8zb2zKw7j8DpO4b4="
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  apt: true
  directories:
    - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh

before_script:
- ./.build_scripts/lint.sh
- npm test
- npm run aggregate_c

script:
- npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: .build_scripts/deploy.sh
  on:
    branch: ${DEPLOY_BRANCH}
