prose:
  metadata:
    app/assets/data/articles:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "tags"
        field:
          element: multiselect
          label: "Tags"
          help: "Select or enter tag names"
          options:
            - name: "baseline"
              value: "baseline"
          alterable: true
